### ISSUE TITLE
Create auto-update script

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoSDR#3]
We'll only be building a new image for new releases instead of for every change.  An auto-update script can keep older images up to date with the git repo until the next image is out or until its flashed.  

- Script should run at boot during S90-S94
- Should be on by default
- Should be able to be disabled w/persistence via settings.sh
- Likely also means adjusting S94pluto-mods to have an earlier start so mods are done and rebooted before the auto-update script fires

**Comment by unixpunk** [comment]
S94pluto-mods will launch S97autoupdate.  readsettings.sh, settings.sh and savenow.sh all updated to include the autoupdate variable.  Just need the actual update mechanism now.

**Comment by unixpunk** [comment]
@ImDroided wget in the image doesn't support https and github only uses https so we need another place with regular http available to store the update.zip and update.zip.md5sum files.  Should we use something on rfoverride?

**Comment by ImDroided** [comment]
Yea we can host it there. You should try to cross compile wget and enable the ssl support option.

**Comment by ImDroided** [comment]
https://unix.stackexchange.com/questions/217028/wget-doesnt-support-https

**Comment by unixpunk** [comment]
@ImDroided I think updates will work now.  Use the plutoweb/buildzip.sh to build your zip and md5 files before your usual git stuff so its uploaded with your changes.  Then reboot your pluto with OTG and see if it gets it.

**Comment by unixpunk** [comment]
Oh and make sure to enable auto-updates and write to nvram first, I forgot its not enabled by default yet.  /etc/motd will show you the status after the updates run.  You can also put an update.zip in /home/friend with scp and it will install it within 20 seconds.  Any change to the overlay folder should include a new zip as long as its tested and you want the change pushed out.

**Comment by unixpunk** [comment]
Tested updating via update.zip sent w/scp.  Haven't yet tested update from update.zip hosted on git.
