### ISSUE TITLE
Push web interface up

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoSDR#4]
Also need to update the dump1090 link on the right to point to the PlutoSDR/dump1090 repo: https://github.com/PlutoSDR/dump1090 since this is the fork I used due to it already having been converted from using rtlsdr to libiio/ad9363.

**Comment by unixpunk** [comment]
Also, don't forget to chmod +x control.cgi

**Comment by unixpunk** [comment]
Make sure you do another pull.  Your index needs to be named index.htm instead of html because the overlay doesn't overwrite the existing file in the image it seems, so now a startup script moves index.htm to index.html and overwrites it each boot instead.  I also +x control.cgi.  commit ce3febaafa78f3536df62b25ac346893ac6ba0f4

dump1090 link still needs updating, that's all on this one I think.

**Comment by ImDroided** [comment]
Fixed

**Comment by unixpunk** [comment]
I updated buildroot/boards/pluto/post-build.sh so it doesn't copy in anything to www anymore.  I also created a symbolic link called index.html that points to index.htm.  I'll leave the overwrite on boot in place for now so keep working in index.htm. 64d7b8d05353e41433eab99f6824419c66a5a4b7
